name: flutter_fusion
description: A flutter project starting point to get started with flutter
  projects with ease and some awesome built in features.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.17
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  path_provider: ^2.1.5
  recase: ^4.1.0

dev_dependencies:
  faker: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  logger: ^2.2.0
  modulr:
    git:
      url: https://github.com/thedevsbuddy/flutter_modulr.git
      ref: v0.1.2

# Launcher Icon Configs
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
